package com.swapnil.bookstore.app.dto;


import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CreateOrderRequest {

    private Long userId;

    /**
     * Unique key generated by client
     * Used to ensure idempotency of order creation
     */
    private String idempotencyKey;
}

